### PR TITLE
Add slash command for attendance

### PR DESCRIPTION
**Pull request by Advayp**
## Changes
- Slash command for attendance
- Mock behavior of API because new engagement routes haven't been merged yet

### CODE REVIEW

**Review by elimelt — COMMENTED** [review]
looks good but let's wait until we are actually calling the endpoint to merge

**Comment by Advayp** [comment]
> looks good but let's wait until we are actually calling the endpoint to merge

Sounds good.

**Comment by Advayp** [comment]
## New Changes
- Call the appropriate engagement point and handle its response

**Review by bhavik-soni — APPROVED** [review]

**Review by elimelt — APPROVED** [review]
LG*TM*

**Pull request merged**
